### ISSUE TITLE
Incomplete Note regarding OpenShift Dev Spaces

### ISSUE THREAD

**Issue by dowinter** [rh-cloud-architecture-workshop/showroom#7]
Hey!

While participating in the workshop an incomplete Note regarding already open OpenShift Dev Spaces Tabs caught my eye. The line in question is the following:
```
[NOTE]
=====
If you already have OpenShift Dev Spaces browser tab accessible, you can directly
=====
```
https://github.com/rh-cloud-architecture-workshop/showroom/blame/a51bc0bf2532e062e11a8cc8cab413f3095228bd/content/modules/ROOT/pages/module-apim-instructions.adoc#L64

I would complete it myself, but I'm not sure about the intention of the note.

**Comment by jayachristina** [comment]
Thank you for bringing this up ..) Will fix this right away! I hope you are enjoying the workshop!

**Comment by jayachristina** [comment]
Corrected.
